project:
  type: website
  output-dir: docs

website:
  title: "Tanveer Singh"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
#      - other.qmd
      - href: resume.qmd
        text: Resume
      
format:
  html:
    theme: Flatly
    css: styles.scss
    mainfont: Source Sans Pro
    toc: true
    page-layout: full

editor: visual

