project:
  type: website
  output-dir: docs

website:
  title: "Tanveer Singh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - other.qmd
      - href: Tanveer_Singh_resume.pdf
        text: Resume
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

